panier:
    path:     /
    defaults: { _controller: EcommerceBundle:Panier:panier }

livraison:
    path:     /livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }

livraisonchoix:
  path: /livraison-choix
  defaults: { _controller: EcommerceBundle:Panier:livraisonChoix }

validation:
    path:     /validation
    defaults: { _controller: EcommerceBundle:Panier:validation }

ajouter:
  path: /ajouter/{id}
  defaults: { _controller: EcommerceBundle:Panier:ajouter }

supprimer:
  path: /supprimer/{id}
  defaults: { _controller: EcommerceBundle:Panier:supprimer }

livraisonAdressesSupression:
  path: /livraison/supprimer/{id}
  defaults: { _controller: EcommerceBundle:Panier:livraisonSupprimer }