produits:
    path:     /
    defaults: { _controller: EcommerceBundle:Produit:produits }

presentation:
    path:     /produit/{id}
    defaults: { _controller: EcommerceBundle:Produit:presentation }

categorieProduits:
    path:     /categorie/{categorie}
    defaults: { _controller: EcommerceBundle:Produit:produits }

rechercheProduits:
    path: /recherche
    defaults: { _controller: EcommerceBundle:Produit:rechercheTraitement }