<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends EntityRepository
{
    public function byFacture($utilisateur)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.utilisateur = :utilisateur')
            ->andWhere('u.valider = 1')
            ->andWhere('u.reference != 0')
            ->orderBy('u.id')
            ->setParameter('utilisateur',$utilisateur);

        return $qb->getQuery()->getResult();
    }

    public function findAllOrderDate($order)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.valider = 1')
            ->orderBy('c.date',$order);

        return $qb->getQuery()->getResult();
    }

    public function findAllValidate()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.valider = 1')
            ->orderBy('c.id');

        return $qb->getQuery()->getResult();
    }
}
